import { AppProvider } from '@toolpad/core/nextjs';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import theme from '@/theme';
import { Metadata } from 'next';
import NAVIGATION from '@/components/Navigation';


export const metadata: Metadata = {
  title: "Ciunac Admin",
  description: "Generated by create next app",
};



export default function RootLayout({ children, }: Readonly<{  children: React.ReactNode; }>) 
{
	return (
		<html lang="en" data-toolpad-color-scheme="light">
			<body>
				<AppRouterCacheProvider options={{ enableCssLayer: true }}>
				<AppProvider theme={theme} navigation={NAVIGATION} branding={{
					logo: <img src="/logo.png" alt="CIUNAC logo" />,
					title: 'CIUNAC ADMIN',
      			}}>
					{children}
				</AppProvider>
				</AppRouterCacheProvider>
			</body>
    	</html>
	);
}
