import { AppProvider } from '@toolpad/core/nextjs';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import theme from '@/theme';
import { Metadata } from 'next';
import NAVIGATION from '@/components/Navigation';
import { SessionProvider, signIn, signOut } from 'next-auth/react';
import { auth } from '@/auth';

export const metadata: Metadata = {
  title: "Ciunac Admin",
  description: "Generated by create next app",
};

const AUTHENTICATION = {
  signIn,
  signOut
}

export default async function RootLayout({ children, }: Readonly<{  children: React.ReactNode; }>) 
{
	const session = await auth()

	return (
		<html lang="en" data-toolpad-color-scheme="light">
			<body>
				<SessionProvider session={session}>
					<AppRouterCacheProvider options={{ enableCssLayer: true }}>
						<AppProvider 
							theme={theme} 
							navigation={NAVIGATION} 
							branding={{
								logo: <img src="/logo.png" alt="CIUNAC logo" />,
								title: 'CIUNAC ADMIN',
							}}
							session={session}
							authentication={AUTHENTICATION}
						>
							{children}
						</AppProvider>
					</AppRouterCacheProvider>
				</SessionProvider>
			</body>
    	</html>
	);
}
